site_name: Aprenda Python com Programação Dinâmica
theme:
  name: material
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-YX74HVMP56
nav:
  - 💻 SOBRE: index.md
  - 🌱 PYTHON DO JEITO CERTO 2.0:
    - pjc2/aula0.md
    - pjc2/aula1.md
    - pjc2/aula2.md
    - pjc2/aula3.md
    - pjc2/aula4.md
    - pjc2/aula5.md
    - pjc2/aula6.md
  - 🎓 PYTHON POR COMPETÊNCIAS: competencias.md
